### PR TITLE
STTR-light inference script update

### PR DESCRIPTION
**Pull request by lebionick**
Edited config for light model launching

### CODE REVIEW

**Comment by cp319** [comment]
I'm sorry, as a beginner, I have some problems. After reading this answer, I made corresponding modifications. But when running ‘STTR-light inference script’, my program reported the following errors.At present, I don't know much about STTR, so I don't know how to modify the parameters.Hope to get your reply。
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Missing key(s) in state_dict: "tokenizer.up.2.convTrans.0.weight", "tokenizer.up.2.convTrans.1.weight", "tokenizer.up.2.convTrans.1.bias", "tokenizer.up.2.convTrans.1.running_mean", "tokenizer.up.2.convTrans.1.running_var", "tokenizer.up.2.convTrans.1.num_batches_tracked", "tokenizer.up.2.convTrans.2.weight", "tokenizer.up.2.convTrans.2.bias", "tokenizer.dense_block.2.double_conv.0.weight", "tokenizer.dense_block.2.double_conv.1.weight", "tokenizer.dense_block.2.double_conv.1.bias", "tokenizer.dense_block.2.double_conv.1.running_mean", "tokenizer.dense_block.2.double_conv.1.running_var", "tokenizer.dense_block.2.double_conv.1.num_batches_tracked", "tokenizer.dense_block.2.double_conv.3.weight", "tokenizer.dense_block.2.double_conv.4.weight", "tokenizer.dense_block.2.double_conv.4.bias", "tokenizer.dense_block.2.double_conv.4.running_mean", "tokenizer.dense_block.2.double_conv.4.running_var", "tokenizer.dense_block.2.double_conv.4.num_batches_tracked". 
   size mismatch for tokenizer.bottle_neck.denselayer1.conv1.weight: copying a param with shape torch.Size([64, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 128, 1, 1]).
   size mismatch for tokenizer.bottle_neck.denselayer1.norm2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).

**Comment by mli0603** [comment]
Hi @cp319, this looks like you are using the wrong model. Can you check if you loaded the right one?

**Comment by cp319** [comment]
Yes, I use model celled  “sttr_light_sceneflow_pretrained_model.pth.tar”  under "inference_example.ipynb". The above problems appear. I have adjusted the number of nheads.

**Comment by cp319** [comment]
> Edited config for light model launching

Hello, excuse me. In addition to adjusting the inference program, whether other programs need to be modified. Is it convenient to provide specific modification methods。

**Comment by mli0603** [comment]
Hi @cp319, can you tell me which file you are trying to run and which branch are you on? I can take a look to see what is wrong.

**Comment by cp319** [comment]
> Hi @cp319, can you tell me which file you are trying to run and which branch are you on? I can take a look to see what is wrong.

I'm trying to run  "scripts/inference_example.ipynb" using "sttr_light_sceneflow_pretrained_model.pth.tar". 
I've changed Densenet's "Growth_Rate" from 4 to 16. And is trying to manually reduce the number of layers of "tokenizer.up"

**Comment by mli0603** [comment]
Hi @cp319 

The `inference_example` is designed to run the **provided** pretrained weights. If you start to modify the growth rate and number of layers, you **CANNOT** use the pretrained weights any more and need to **retrain** the network with the parameters you specified.

**Pull request merged**
